<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <PackageId>TinyMCE.Blazor</PackageId>
    <Version>2.2.1</Version>
    <Authors>Ephox Corporation DBA Tiny Technologies, Inc.</Authors>
    <Company>Ephox Corporation DBA Tiny Technologies, Inc.</Company>
    <PackageTags>tinymce;blazor;component;wysiwyg;rich-text-editor;html;dotnet;razor;contenteditable;blazor-component;text-editor</PackageTags>
    <Description>Official Blazor component for TinyMCE rich text editor.</Description>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <RazorLangVersion>3.0</RazorLangVersion>
    <RepositoryUrl>https://github.com/tinymce/tinymce-blazor</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>tiny-icon.png</PackageIcon>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../CHANGELOG.md"))</PackageReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.0" Condition="'$(TargetFramework)' == 'net8.0'" />
    <None Include="../LICENSE.txt" pack="true" PackagePath="" />
    <None Include="../README.md" pack="true" PackagePath="" />
    <None Include="../tiny-icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
